import{a as w,i as g,S as v}from"./assets/vendor-DEenWwFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const E="48273516-22e71b99033a61f3653b23d90",b="https://pixabay.com/api/",$=15;async function f(o,r=1){try{const t=`${b}?key=${E}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${$}&page=${r}`,e=(await w.get(t)).data;if(e.hits.length===0)throw new Error("No images found");return{images:e.hits,totalHits:e.totalHits}}catch(t){throw console.error("Ошибка запроса:",t),t}}function m(o,r=!1){const t=document.querySelector(".gallery"),n=o.map(e=>`
    <div class="gallery-item">
      <a href="${e.largeImageURL}" class="gallery-link">
        <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" />
      </a>
      <div class="image-info">
        <p><strong>Likes:</strong> ${e.likes}</p>
        <p><strong>Views:</strong> ${e.views}</p>
        <p><strong>Comments:</strong> ${e.comments}</p>
        <p><strong>Downloads:</strong> ${e.downloads}</p>
      </div>
    </div>
  `).join("");r?t.insertAdjacentHTML("beforeend",n):t.innerHTML=n}function a(o){g.error({title:"Error",message:o,position:"topRight"})}function h(){document.querySelector(".loader").classList.remove("hidden")}function y(){document.querySelector(".loader").classList.add("hidden")}const P=document.getElementById("search-form"),q=document.getElementById("search-input"),I=document.querySelector(".gallery"),c=document.getElementById("load-more");let p=null,d="",i=1;const L=15;let u=0;P.addEventListener("submit",async o=>{o.preventDefault();const r=q.value.trim();if(r===""){a("Please enter a search query");return}d=r,i=1,I.innerHTML="",c.classList.add("hidden"),h();try{const{images:t,totalHits:n}=await f(d,i);if(u=n,t.length===0){a("Sorry, there are no images matching your search query. Please try again!");return}m(t),p=new v(".gallery a").refresh(),u>L&&c.classList.remove("hidden")}catch{a("An error occurred. Please try again later.")}finally{y()}});c.addEventListener("click",async()=>{i+=1,h();try{const{images:o}=await f(d,i);m(o,!0),p.refresh();const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),i*L>=u&&(c.classList.add("hidden"),g.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a("An error occurred while loading more images.")}finally{y()}});
//# sourceMappingURL=index.js.map
