import{i as g,S as w}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function t(e){if(e.ep)return;e.ep=!0;const n=s(e);fetch(e.href,n)}})();const v="48273516-22e71b99033a61f3653b23d90",b="https://pixabay.com/api/";function f(o,r=1){const s=`${b}?key=${v}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`;return fetch(s).then(t=>{if(!t.ok)throw new Error("Network response was not ok");return t.json()}).then(t=>{if(t.hits.length===0)throw new Error("No images found");return{hits:t.hits,totalHits:t.totalHits}})}function h(o,r=!1){const s=document.querySelector(".gallery"),t=o.map(e=>`
    <div class="gallery-item">
      <a href="${e.largeImageURL}" class="gallery-link">
        <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" />
      </a>
      <div class="image-info">
        <p><strong>Likes:</strong> ${e.likes}</p>
        <p><strong>Views:</strong> ${e.views}</p>
        <p><strong>Comments:</strong> ${e.comments}</p>
        <p><strong>Downloads:</strong> ${e.downloads}</p>
      </div>
    </div>
  `).join("");r?s.insertAdjacentHTML("beforeend",t):s.innerHTML=t}function a(o){g.error({title:"Error",message:o,position:"topRight"})}function m(){document.querySelector(".loader").classList.remove("hidden")}function y(){document.querySelector(".loader").classList.add("hidden")}const E=document.getElementById("search-form"),$=document.getElementById("search-input"),q=document.querySelector(".gallery"),l=document.getElementById("load-more");let p=null,d="",i=1;const L=15;let u=0;E.addEventListener("submit",async o=>{o.preventDefault();const r=$.value.trim();if(r===""){a("Please enter a search query");return}d=r,i=1,q.innerHTML="",l.classList.add("hidden"),m();try{const{hits:s,totalHits:t}=await f(d,i);if(u=t,s.length===0){a("Sorry, there are no images matching your search query. Please try again!");return}h(s),p=new w(".gallery a").refresh(),u>L&&l.classList.remove("hidden")}catch{a("An error occurred. Please try again later.")}finally{y()}});l.addEventListener("click",async()=>{i+=1,m();try{const{hits:o}=await f(d,i);h(o,!0),p.refresh();const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),i*L>=u&&(l.classList.add("hidden"),g.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a("An error occurred while loading more images.")}finally{y()}});
//# sourceMappingURL=index.js.map
